<?php

namespace App\Models;

use App\Observers\MainCatidoryObserve;
use Illuminate\Database\Eloquent\Model;

class Main_categorie extends Model
{
    protected $table="main_categories";
    protected $fillable=['id','translation_lang','translation_of','name','slug','photo','active','created_at','updated_at'];
    protected $hidden=['created_at','updated_at'];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Main_categorie::observe(MainCatidoryObserve::class);
    }

    public function scopeActive($query){
    return $query->where('active',1);
}
    public function scopeDefaultCategorie($query){
        return $query->where('translation_of',0);
    }
    public function getActiveAttribute($val){
        return $val==1 ? 'مفعل' : 'غير مفعل';
    }
    public function getPhotoAttribute($val){
        return $val!=null ? asset('admin\image\upload\main_categories\\'.$val) : '';
    }

    ################################ relations###############################
    public function vendors(){
       return $this->hasMany('App\Models\Vendor','categorie_id','id');
    }
    public function categories(){
        return $this->hasMany(self::class,'translation_of');
    }

    ################################ end relations###############################
}
